apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{include "frontend.fullname" . }}
spec:
  host: {{include "frontend.fullname" .}}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: prod
      labels:
        version: prod
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{include "backend.fullname" . }}
spec:
  host: {{include "backend.fullname" .}}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: prod
      labels:
        version: prod
    - name: canary
      labels:
        version: canary
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{include "database.fullname" . }}
spec:
  host: {{include "database.fullname" .}}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: prod
      labels:
        version: prod